version: '3.8'

services:
  frontend:
    build:
      context: ./TODO/todo_frontend
    ports:
      - "80:80" # Map port 80 on the VM to port 80 in the container
    environment:
      - REACT_APP_API_URL=http://backend:5000 # Configure backend URL for API requests
    depends_on:
      - backend

  backend:
    build:
      context: ./TODO/todo_backend
    ports:
      - "5000:5000" # Map port 5000 on the VM to port 5000 in the container
    environment:
      - PORT=5000 # Ensure the backend runs on port 5000
